function DungeonScene_Tutorial_D001_F01_R01()
  -- CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -2131507527)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1712785416)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1295670213)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1411476102)
  -- WINDOW:Talk(SymAct("KONOHANA"), -459340867)
  -- WINDOW:Talk(SymAct("KONOHANA"), -41667844)
  -- WINDOW:Talk(SymAct("KONOHANA"), -693542593)
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  -- CH("KONOHANA"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- CH("KONOHANA"):WaitRotate()
end
function DungeonScene_Tutorial_D001_F01_R02()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  -- CH("KONOHANA"):WaitManpu()
  -- CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  -- CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("KONOHANA"), -810397570)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1210731697)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1362198000)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1629729262)
  -- WINDOW:Talk(SymAct("KONOHANA"), 2016968879)
  -- WINDOW:CloseMessage()
  -- CH("HERO"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- CH("KONOHANA"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D001_F01_R03()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("KONOHANA"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  -- CH("KONOHANA"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1393939308)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1242489389)
  -- WINDOW:Talk(SymAct("KONOHANA"), 89093354)
  WINDOW:Talk(SymAct("KONOHANA"), 475284907)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D001_F01_R03_WARN01()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 930682472)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 778184489)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D001_F01_R03_WARN02()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KONOHANA"), -1443218458)
  WINDOW:Talk(SymAct("KONOHANA"), -1327428953)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D001_F01_R03_WARN03()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.EMOTION)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1939217920)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1787637569)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1101036674)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1488670147)
  -- WINDOW:CloseMessage()
  CH("KONOHANA"):WaitRotate()
end
function DungeonScene_Tutorial_D001_F01_R04()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 402316036)
  -- WINDOW:Talk(SymAct("KONOHANA"), 249686597)
  WINDOW:Talk(SymAct("KONOHANA"), 634173830)
  WINDOW:CloseMessage()
  CH("HERO"):WaitRotate()
  CH("KONOHANA"):WaitRotate()
end
function DungeonScene_Tutorial_D001_F01_R04_WARN01()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 1020758215)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D001_F01_R04_WARN02()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -1152412664)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D001_F01_R04_END()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1571510967)
  -- WINDOW:Talk(SymAct("KONOHANA"), -886408859)
  -- WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D001_F01_R05()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("KONOHANA"):SetManpu("MP_SPREE_LP")
  -- CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.GLADNESS)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.GLADNESS)
  -- WINDOW:Talk(SymAct("KONOHANA"), -768522204)
  -- WINDOW:KeyWait()
  -- CH("KONOHANA"):ResetManpu()
  -- CH("KONOHANA"):ResetFacialMotion()
 WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -115598361)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D001_F02_R01()
  -- CH("KONOHANA"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(1))
  -- subEveLookAround(CH("KONOHANA"), Speed(600))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  -- CH("KONOHANA"):WaitManpu()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("KONOHANA"), -536401242)
  -- WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1354318751)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1235383008)
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
end
function DungeonScene_Tutorial_D002_F01_R01()
  -- CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  -- CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1653547293)
  -- WINDOW:Talk(SymAct("KONOHANA"), -2073301086)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 66319213)
  -- WINDOW:Talk(SymAct("KONOHANA"), 451461676)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1459438044)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1340502173)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1691034462)
  -- WINDOW:Talk(SymAct("KONOHANA"), 2110788127)
  -- WINDOW:CloseMessage()
  -- subEveNod(CH("HERO"))
  CH("HERO"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(RotateTarget(180), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D002_F01_R02()
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  -- CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  -- CH("KONOHANA"):WaitManpu()
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  -- WINDOW:Talk(SymAct("KONOHANA"), 848397528)
  -- WINDOW:Talk(SymAct("KONOHANA"), 730510745)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 11003482)
  -- WINDOW:Talk(SymAct("KONOHANA"), 431806235)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1641755692)
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D002_F01_R02_SWING()
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -2025850219)
  -- WINDOW:Talk(SymAct("KONOHANA"), -297720135)
  -- WINDOW:CloseMessage()
  -- TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D002_F01_R03()
  -- CH("KONOHANA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  -- CH("KONOHANA"):WaitRotate()
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -145090568)
  -- WINDOW:Talk(SymAct("KONOHANA"), -596163525)
  -- WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("HERO"):WaitRotate()
  CH("KONOHANA"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -982747782)
  WINDOW:Talk(SymAct("KONOHANA"), -1976704067)
  WINDOW:CloseMessage()
  CH("HERO"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D002_F01_R03_WARN01()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_01"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  CH("KONOHANA"):WaitManpu()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -1825123588)
  WINDOW:Talk(SymAct("KONOHANA"), -1206156993)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R03_WARN02()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -1593790338)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R03_02()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 647539889)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R03_OUT()
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1065590256)
  -- WINDOW:CloseMessage()
  -- CH("KONOHANA"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -51082921)
  -- WINDOW:Talk(SymAct("KONOHANA"), -437274602)
  -- WINDOW:Talk(SymAct("KONOHANA"), -826086443)
  -- WINDOW:Talk(SymAct("KONOHANA"), -673588588)
  -- WINDOW:CloseMessage()
  -- CH("KONOHANA"):DirTo(RotateTarget(-90), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D002_F01_R03_OUT_WARN01()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1734849453)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04()
  CH("KONOHANA"):DirTo(RotateTarget(90), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.3))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -2122089198)
  -- WINDOW:Talk(SymAct("KONOHANA"), -1431425327)
  WINDOW:Talk(SymAct("KONOHANA"), -1279975536)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_02()
  -- CH("KONOHANA"):SetManpu("MP_LAUGH_LP")
  -- CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("KONOHANA"), 875365215)
  -- WINDOW:CloseMessage()
  -- WINDOW:KeyWait()
  -- CH("KONOHANA"):ResetFacialMotion()
  -- CH("KONOHANA"):ResetManpu()
  -- TASK:Sleep(TimeSec(0.8))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 758526494)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1145630258)
  WINDOW:Talk(SymAct("KONOHANA"), 1565777779)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_MISS_01()
  CH("KONOHANA"):SetManpu("MP_LAUGH_LP")
  CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  WINDOW:Talk(SymAct("KONOHANA"), 1988005040)
  WINDOW:Talk(SymAct("KONOHANA"), 1868938737)
  WINDOW:CloseMessage()
  WINDOW:KeyWait()
  CH("KONOHANA"):ResetFacialMotion()
  CH("KONOHANA"):ResetManpu()
  TASK:Sleep(TimeSec(0.8))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 539241270)
  WINDOW:Talk(SymAct("KONOHANA"), 960436855)
  WINDOW:Talk(SymAct("KONOHANA"), 303188404)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_WARN01()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 185170165)
  WINDOW:Talk(SymAct("KONOHANA"), -1936628678)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_WARN01_MISS_00()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -1786096261)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_03()
  -- CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(0.3))
  -- CH("KONOHANA"):SetManpu("MP_SPREE_LP")
  -- CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("KONOHANA"), 472645220)
  -- WINDOW:CloseMessage()
  -- CH("KONOHANA"):ResetFacialMotion()
  -- CH("KONOHANA"):ResetManpu()
  -- TASK:Sleep(TimeSec(0.5))
  -- CH("KONOHANA"):DirTo(RotateTarget(-90), Speed(350), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(1))
  -- subEveLookAround(CH("KONOHANA"), Speed(600))
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.8))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), 87084837)
  -- WINDOW:Talk(SymAct("KONOHANA"), 773692646)
  WINDOW:Talk(SymAct("KONOHANA"), 923184551)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_WARN02()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), 2017934176)
  WINDOW:Talk(SymAct("KONOHANA"), 1633421857)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), 1248942562)
  WINDOW:Talk(SymAct("KONOHANA"), 1399482531)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_WARN03()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  CH("KONOHANA"):WaitManpu()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.SURPRISE)
  WINDOW:Talk(SymAct("KONOHANA"), -722307988)
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  WINDOW:Talk(SymAct("KONOHANA"), -840350419)
  WINDOW:Talk(SymAct("KONOHANA"), -1533568767)
  WINDOW:Talk(SymAct("KONOHANA"), -1114855360)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_WARN04()
  SOUND:PlaySe(SymSnd("SE_EVT_SIGN_SHOCK_02"), Volume(256))
  CH("KONOHANA"):SetManpu("MP_SHOCK_R")
  CH("KONOHANA"):WaitManpu()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("KONOHANA"), -1767769213)
  WINDOW:Talk(SymAct("KONOHANA"), -1883583806)
  WINDOW:Talk(SymAct("KONOHANA"), -1057268731)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F01_R04_SWAP()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(350), ROT_TYPE.NEAR)
  -- CH("KONOHANA"):WaitRotate()
  -- CH("KONOHANA"):SetFacialMotion(FACIAL_MOTION.HAPPY)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("KONOHANA"), -639603388)
  -- WINDOW:CloseMessage()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(350), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):WaitRotate()
  -- TASK:Sleep(TimeSec(0.4))
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.HAPPY)
  -- WINDOW:Talk(SymAct("KONOHANA"), -221430137)
  -- WINDOW:KeyWait()
  -- CH("KONOHANA"):ResetFacialMotion()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.NORMAL)
  -- WINDOW:Talk(SymAct("KONOHANA"), -338292794)
  WINDOW:Talk(SymAct("KONOHANA"), 1817056009)
  WINDOW:CloseMessage()
end
function DungeonScene_Tutorial_D002_F02_R01()
  -- CH("KONOHANA"):DirTo(RotateTarget(0), Speed(500), ROT_TYPE.NEAR)
  -- TASK:Sleep(TimeSec(1))
  -- subEveLookAround(CH("KONOHANA"), Speed(600))
  -- SOUND:PlaySe(SymSnd("SE_EVT_SIGN_HURRY"), Volume(256))
  -- CH("KONOHANA"):SetManpu("MP_FLY_SWEAT")
  -- CH("KONOHANA"):WaitManpu()
  CH("HERO"):DirTo(CH("KONOHANA"), Speed(500), ROT_TYPE.NEAR)
  -- WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("KONOHANA"), 1968513608)
  -- WINDOW:Talk(SymAct("KONOHANA"), -503048105)
  -- WINDOW:CloseMessage()
  CH("KONOHANA"):DirTo(CH("HERO"), Speed(500), ROT_TYPE.NEAR)
  CH("KONOHANA"):WaitRotate()
  CH("HERO"):WaitRotate()
  WINDOW:DrawFace(324, 88, SymAct("KONOHANA"), FACE_TYPE.PAIN)
  -- WINDOW:Talk(SymAct("KONOHANA"), -81843946)
  WINDOW:Talk(SymAct("KONOHANA"), -801998123)
  WINDOW:CloseMessage()
  subEveNod(CH("HERO"))
end
function DungeonScene_Tutorial_D032_S01_C01()
  WINDOW:SysMsg(-920040556)
  WINDOW:SysMsg(-2039947949)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(-1619792878)
  WINDOW:SysMsg(-1268858927)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D032_S01_C02()
  WINDOW:SysMsg(-1387950448)
end
function DungeonScene_Tutorial_D032_S01_C02_RETRY()
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(719163999)
  WINDOW:SysMsg(868655902)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
end
function DungeonScene_Tutorial_D032_S01_C03()
  WINDOW:ForceCloseMessage()
  TASK:Sleep(TimeSec(0.5))
  WINDOW:SysMsg(1522040626)
  WINDOW:SysMsg(1134775923)
  WINDOW:SysMsg(1754144176)
end
function DungeonScene_Tutorial_D032_S01_C04()
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(1905601777)
end
function DungeonScene_Tutorial_D032_S01_C05()
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(1054128694)
end
function DungeonScene_Tutorial_D032_S01_C06()
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(667913079)
end
function DungeonScene_Tutorial_D032_S01_C07()
  WINDOW:SysMsg(216193204)
end
function DungeonScene_Tutorial_D032_S01_C08()
  WINDOW:ForceCloseMessage()
end
function DungeonScene_Tutorial_D032_S01_C081()
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 368699893)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.PAIN)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1839073990)
  WINDOW:DrawFace(20, 88, SymAct("MIRUHOGGU"), FACE_TYPE.SHOUT)
  WINDOW:Talk(SymAct("MIRUHOGGU"), -1954888581)
  WINDOW:Talk(SymAct("MIRUHOGGU"), 1208864988)
  WINDOW:CloseMessage()
  TASK:Sleep(TimeSec(0.3))
  WINDOW:SysMsg(1360454045)
end
function DungeonScene_Tutorial_D032_S01_C09()
  WINDOW:SysMsg(2050732638)
end
function DungeonScene_Tutorial_D032_S01_C09_RETRY()
  WINDOW:ForceCloseMessage()
  WINDOW:SysMsg(1663075103)
end
function DungeonScene_Tutorial_D032_S01_C10()
  WINDOW:ForceCloseMessage()
end
function DungeonScene_Tutorial_D032_S01_C11()
  WINDOW:SysMsg(744560088)
end
function DungeonScene_Tutorial_D032_S01_C12()
  WINDOW:ForceCloseMessage()
end
function DungeonScene_Tutorial_D032_S01_C13()
  WINDOW:SysMsg(897197209)
  WINDOW:CloseMessage()
end
function DungeonScene_BossHouou()
  CUT:Load(SymCut("qb01_houou"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossFriizaa()
  CUT:Load(SymCut("qb02_furiizaa"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossSandaa()
  CUT:Load(SymCut("qb03_sandaa"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossFaiyaa()
  CUT:Load(SymCut("qb04_faiyaa"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossRugia()
  CUT:Load(SymCut("qb05_rugia"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossDaakurai()
  CUT:Load(SymCut("qb06_daakurai"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_IBERUTARU"), Volume(256))
end
function DungeonScene_BossKyuremu()
  CUT:Load(SymCut("qb07_kyuremu"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_KYUREMU"), Volume(256))
end
function DungeonScene_BossKyuremu_black()
  CUT:Load(SymCut("qb08a_Kyuremu_black"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_IBERUTARU"), Volume(256))
end
function DungeonScene_BossKyuremu_white()
  CUT:Load(SymCut("qb08b_kyuremu_white"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_IBERUTARU"), Volume(256))
end
function DungeonScene_BossKaiooga()
  CUT:Load(SymCut("qb09_kaiooga"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_01"), Volume(256))
end
function DungeonScene_BossGuraadon()
  CUT:Load(SymCut("qb10_guraadon"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_01"), Volume(256))
end
function DungeonScene_BossMyuutsuu()
  CUT:Load(SymCut("qb11a_myuutsuu"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossMyuutsuu_x()
  CUT:Load(SymCut("qb11b_myuutsuu_x"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_04_OLD"), Volume(256))
end
function DungeonScene_BossMyuutsuu_y()
  CUT:Load(SymCut("qb11c_myuutsuu_y"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_04_OLD"), Volume(256))
end
function DungeonScene_BossKobaruon()
  CUT:Load(SymCut("qb12_kobaruon"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_02_ROCK"), Volume(256))
end
function DungeonScene_BossZekuromu()
  CUT:Load(SymCut("qb13_zekuromu"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_03"), Volume(256))
end
function DungeonScene_BossRejisuchiru()
  CUT:Load(SymCut("qb14_rejisuchiru"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossRejirokku()
  CUT:Load(SymCut("qb15_rejirokku"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossRejiaisu()
  CUT:Load(SymCut("qb16_rejiaisu"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossRejigigasu()
  CUT:Load(SymCut("qb17_rejigigasu"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossDiaruga()
  CUT:Load(SymCut("qb18_diaruga"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_DLC_024"), Volume(256))
end
function DungeonScene_BossParukia()
  CUT:Load(SymCut("qb19_parukia"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossGiratyina_o()
  CUT:Load(SymCut("qb20_giratyina_o"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_DENSETSU"), Volume(256))
end
function DungeonScene_BossRekkuuza()
  CUT:Load(SymCut("qb21a_rekkuuza"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_EVE_BOSS_HYOUSHOKU_01"), Volume(256))
end
function DungeonScene_BossRekkuuza_mega()
  CUT:Load(SymCut("qb21b_rekkuuza_mega"))
  CAMERA:SetSisaAzimuthDifferenceVolume(Volume(0.5))
  CAMERA:SetSisaRateVolume(Volume(1))
  CUT:Play()
  CUT:Wait()
  CUT:Destroy()
  EFFECT:BossWipeWait()
  SOUND:PlayBgm(SymSnd("BGM_DLC_002"), Volume(256))
end
function DungeonScene_BossWipe()
  SOUND:PlaySe(SymSnd("SE_EVT_BOSS_WIPE"), Volume(256))
  EFFECT:BossWipe(TimeSec(60, TIME_TYPE.FRAME), false)
end

